### ISSUE TITLE
Will this package support Laravel 9?

### ISSUE THREAD

**Issue by LukeTowers** [luisdalmolin/laravel-mandrill-driver#25]
Laravel 9 moved to Symfony Mailer, see https://github.com/laravel/framework/pull/38481

**Comment by therobfonz** [comment]
I don't really use Mandrill anymore, but I do plan on supporting Laravel 9, although it might not be right away. I will of course accept any PRs from people who use the package daily and can test easier than I can since I no longer have Mandrill access.

**Comment by nickurt** [comment]
@LukeTowers You can use [symfony/mailchimp-mailer](https://github.com/symfony/mailchimp-mailer)

**Comment by ajsheldon93** [comment]
Confirmed that this package doesn't work in L9, but you can just use the builtin SMTP instead. Credentials are under "settings" in your mandrillapp.com dashboard. Seems to work fine.

**Comment by therobfonz** [comment]
Thanks everyone! In the process of transferring this package to someone who uses Mandrill still. It will have a new maintainer in the coming days who will do the Laravel 9 upgrade.

**Comment by JayBizzle** [comment]
> Thanks everyone! In the process of transferring this package to someone who uses Mandrill still. It will have a new maintainer in the coming days who will do the Laravel 9 upgrade.

Any updates on the new maintainer?

**Comment by brandonferens** [comment]
Yes, we just merged a PR for the upgrade to Laravel 9. Please update your composer.json to require `^4.0.0`.
