### ISSUE TITLE
No longer maintained?

### ISSUE THREAD

**Issue by wblommaert** [luisdalmolin/laravel-mandrill-driver#36]
My apologies if this is just a false impression, but it seems nobody is following up on the issues and open pull requests. We use this package in all of our Laravel projects and have currently resorted to a fork (#34) of a fork (#33) to be able to use it properly in Laravel 9. Could you shed some light on the current maintainer situation? Would you be interested in getting more maintainers onboard to follow up on the issue tracker and pull requests?

Regardless of the above, thank you for keeping this package available after the recent transfer.

**Comment by brunocbatista** [comment]
Hi, is there any solution for this?

**Comment by luisdalmolin** [comment]
I merged and tagged the PR, sorry for the delay. Thanks for the contribution.
