### ISSUE TITLE
Laravel framwork 7 composer error

### ISSUE THREAD

**Issue by Jesper-FIltenborg-Dwarf** [luisdalmolin/laravel-mandrill-driver#37]
When i run composer update with following.

- "therobfonz/laravel-mandrill-driver": "^3.0",
- "laravel/framework": "^7.29",

It either fail on the php version, Im running 8.0 (^3.0 composer not accepting ^8.0) due to some other packages, or it fail due to illuminate/support is required ^9.0 but laravel 7.2 requires another version therefore generating a conflict

**Comment by luisdalmolin** [comment]
Yeah, the PHP version is locked to 7.* on version 3. I'll push an update to this version

**Comment by luisdalmolin** [comment]
Nevermind, version 3 supports PHP 8.0 (https://github.com/luisdalmolin/laravel-mandrill-driver/blob/v3.1.0/composer.json), so it's likely failing because of a different dependency.
