### ISSUE TITLE
Laravel 11 Support?

### ISSUE THREAD

**Issue by bjmcatilo29** [luisdalmolin/laravel-mandrill-driver#42]

**Comment by bjmcatilo29** [comment]
Will you still be supporting laravel 11?

**Comment by davidhsianturi** [comment]
@luisdalmolin any plan for this?

**Comment by luisdalmolin** [comment]
Yes, I can add support for it this weekend. If it is pressing, feel free to submit a PR.

**Comment by luisdalmolin** [comment]
Just tagged a new version with Laravel 11 support.

**Comment by bjmcatilo29** [comment]
hi @luisdalmolin i think mailer version should be 7.0.

**Comment by luisdalmolin** [comment]
Done: https://github.com/luisdalmolin/laravel-mandrill-driver/releases/tag/6.0.0
