### ISSUE TITLE
Can't upgrade to Laravel 11

### ISSUE THREAD

**Issue by Azoorb** [luisdalmolin/laravel-mandrill-driver#43]
Hello ! 

I can't upgrade to Laravel 11 with the v5.1 of this package because laravel 11 need symfony/mailer:^7.0 but it is lock to ^6.0 in composer.json

` therobfonz/laravel-mandrill-driver 5.1.0 requires symfony/mailer ^6.0 -> found symfony/mailer[v6.0.0, ..., v6.4.4] but the package is fixed to v7.0.4`

Maybe juste upgrade the composer.json ? 

Thanks you !

**Comment by luisdalmolin** [comment]
Done: https://github.com/luisdalmolin/laravel-mandrill-driver/releases/tag/6.0.0
